### ISSUE TITLE
Mocha tests with Babel 6 problems

### ISSUE THREAD

**Issue by ndjordjevic** [pghalliday/grunt-mocha-test#118] opened 2016-03-17 22:15 UTC
Hi, I got the following error when I run tests:

Files: server/api/thing/index.spec.js, server/api/user/index.spec.js, server/api/user/user.model.spec.js
Options: reporter="spec", require="mocha.conf.js", timeout=5000
>> Mocha exploded!
>> TypeError: require(...) is not a function
>>     at Object.<anonymous> (app.js:30:1)
>>     at Module._compile (module.js:413:34)
>>     at loader (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:126:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:136:7)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (index.js:12:28)
>>     at Module._compile (module.js:413:34)
>>     at loader (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:126:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:136:7)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)
>>     at Module.require (module.js:367:17)
>>     at require (internal/module.js:16:19)
>>     at Object.<anonymous> (user.model.spec.js:3:1)
>>     at Module._compile (module.js:413:34)
>>     at loader (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:126:5)
>>     at Object.require.extensions.(anonymous function) [as .js] (/Users/ndjordjevic/IdeaProjects/medical-rec5/node_modules/babel-register/lib/node.js:136:7)
>>     at Module.load (module.js:357:32)
>>     at Function.Module._load (module.js:314:12)

The extract from Gruntfile.js:
   `` mochaTest: {
      options: {
        reporter: 'spec',
        require: 'mocha.conf.js',
        timeout: 5000
      },
      unit: {
        src: ['<%= yeoman.server %>/**/*.spec.js']
      }, ... ``

And mocha.conf.js:
```javascript
'use` strict';

// Register the Babel require hook
require("babel-register");

var chai = require('chai');

// Load Chai assertions
global.expect = chai.expect;
global.assert = chai.assert;
chai.should();

// Load Sinon
global.sinon = require('sinon');

// Initialize Chai plugins
chai.use(require('sinon-chai'));
chai.use(require('chai-as-promised'));
chai.use(require('chai-things'))`
```
I'm using the latest versions of node, npm and all deps.
When the tests are run manually everything works fine.

**Comment by pghalliday** [comment] 2016-03-27 08:05
I can't reproduce this - maybe you could point me at your actual project?

**Comment by ndjordjevic** [comment] 2016-03-27 17:09
Here it is:
https://github.com/ndjordjevic/medical-rec5

**Comment by pghalliday** [comment] 2016-03-29 08:00
ok i think that's too big for me to debug and requires me to install stuff globally (not happening). Can you reproduce the issue in a simpler scenario?

**Comment by pghalliday** [comment] 2016-09-18 10:50
closing as old

**Closed by pghalliday** 2016-09-18 10:50 UTC
