### ISSUE TITLE
grunt-mocha-test has problems with grunt-contrib-watch with livereload on

### ISSUE THREAD

**Issue by poxu** [pghalliday/grunt-mocha-test#104] opened 2015-09-21 13:01 UTC
Problem
----------
If livereload for grunt-contrib-watch is on, then watch shuts down after the second change among watched files.

Environment
---------------
Os - Windows 8.1
node version - 4.1.0

Steps to reproduce
------------------------
1. Create a project with a single test, which always passes
2. Add Gruntfile.js as described in Readme.md 
3. Set livereload to any port you want
4  Set spawn to false
5. Run npm install
6. Run grunt watch
7. Open Gruntfile.js and save it
8. Save it again

Expected result
-------------------
Tests run two times with identical results

Actual result
----------------

Reloading watch config...

Running "watch" task
Waiting...
Fatal error: Port 12345 is already in use by another process.

Additional info
-----------------
Port number doesn't matter
If spawn is set to true, the problem is not reproduced
I can provide an archive with a test project to reproduce the problem

**Comment by pghalliday** [comment] 2015-09-21 23:21
if you could submit the sample project that would be great. The error being about a port already in use suggests it may be a problem with the way you are integrating `livereload` and not `grunt-mocha-test`.
Also the `spawn` option is a `grunt-contrib-watch` option, so it doesn't look like `grunt-mocha-test` is linked to either the symptom or the workaround. Do you have watch starting livereload? If so I suspect that as you don't spawn a new process, then the previous livereload job is still running and so the port is still in use

**Comment by poxu** [comment] 2015-09-22 09:41
Here's the project to reproduce the issue: https://github.com/poxu/grunt-mocha-test-livereload
Maybe it's a **grunt-contrib-watch** issue, but if I run **grunt-contrib-watch** with **jshint** or with *grunt-mocha* it doesn't show itself.

**Comment by pghalliday** [comment] 2015-09-25 07:39
ok thanks. The problem is the `clearRequireCache` option. This causes grunt to forget it already started livereload (I think). I don't have a solution right now, but I think it would be nicer if `grunt-contrib-watch` were not stateful in this way.

I think the best solution is to stop setting `spawn` to `false`. In my experience this always causes problems (and is the reason for the `clearRequireCache` option).

I am open to creative pull requests to improve the `clearRequireCache` behaviour. I have been considering adding an exclude option to that so that not everything gets cleared.

**Comment by poxu** [comment] 2015-09-28 14:16
Thanks a lot for clarifying the matter! I'll use setting spawn to false as a workaround and I'll submit a pull request if I have ideas how to make things better.

**Comment by pghalliday** [comment] 2015-10-19 09:21
I'm going to close this as won't fix - it's unlikely that I will ever get round to working out and implementing a sane solution to this caching problem. Thanks for reporting it though, it's another gotcha that's worth keeping a record of

**Closed by pghalliday** 2015-10-19 09:21 UTC
