### ISSUE TITLE
Multiple reporters

### ISSUE THREAD

**Issue by naando-araujo** [pghalliday/grunt-mocha-test#105] opened 2015-09-23 18:32 UTC
Hi,
How about change options.reporter for an array?

Thanks

**Comment by pghalliday** [comment] 2015-09-24 11:50
i don't think `mocha` supports multiple reporters. I have used the `mocha-multi` module to add this functionality in the past

https://www.npmjs.com/package/mocha-multi

**Comment by naando-araujo** [comment] 2015-09-24 18:08
In fact, I did a little research and it's came up before create this, but the ideia is we find a way to workaround while it's not supported. I read here that's a day we'll have it in production: http://www.juliengilli.com/2013/12/14/Using-multiple-reporters-with-Mocha/
What do you think?

**Comment by pghalliday** [comment] 2015-09-25 07:17
tbh, I think the workaround is to use `mocha-multi`, I haven't tried it in a config of my own. But I think it will work if you add your task like this:

```
    // Configure a mochaTest task
    mochaTest: {
      test: {
        options: {
          reporter: 'mocha-multi',
          reporterOptions: {
            Progress:{ 
              stdout:"/tmp/mocha-multi.Progress.out",
              options: {
                verbose: true
              }
           },
           spec: {
              stdout:"-"
           }
        },
        src: ['test/**/*.js']
      }
    }
```

Derived from the programatic example on the `mocha-multi` README. It should work because the options block here will be passed directly to the mocha constructor

**Comment by naando-araujo** [comment] 2015-09-25 12:21
Great! I'll try it when possible and return a feedback soon.
Thanks!

**Comment by naando-araujo** [comment] 2015-09-25 13:12
I believe that was close, although I don't know all the workflow behind the scenes and didn't work exactly as expected, my config:
<pre>mochaTest: {
    test: {
        src: watchFiles.mochaTests
        , options: {
            require: 'server.js'

            //, reporter: 'spec' // doc
            //, captureFile: 'report/mocha.txt' // html

            , reporter: 'mocha-multi'
            , reporterOptions: {
                Progress:{
                    stdout: 'report/mocha.txt',
                    //stdout:"-",
                    options: {
                        verbose: true
                    }
                },
                spec: {
                    stdout:"-"
                }
            }
        }
    }
    , coverage: {
        options: {
            reporter: 'html-cov',
            quiet: true,
            captureFile: 'report/coverage/back/mocha_result.html'
        },
        src: [
            //'app/**/*.js'

            'app/tests/*.js'

            //'app/controllers/**/*.js'
            //, 'app/models/**/*.js'
            //, 'app/modules/**/*.js'
            //, 'app/routes/**/*.js'
        ]
    }
}</pre>

If I use `reporter: 'mocha-multi'` the task is not finished, I run my grunt but the console doesn't return.
With `reporter: 'spec'`it's ok.

Thanks

**Comment by pghalliday** [comment] 2015-09-26 10:47
I just tested with this project

https://github.com/pghalliday/grunt-mocha-multi

Worked fine for me

**Comment by pghalliday** [comment] 2015-10-19 09:18
Closing as not reproducible

**Closed by pghalliday** 2015-10-19 09:18 UTC
