### ISSUE TITLE
Latest version of Coffeescript

### ISSUE THREAD

**Issue by ghostsquad** [pghalliday/grunt-mocha-test#106] opened 2015-09-28 16:01 UTC
Coffeescript is up to version 1.10
this is using 1.8

**Comment by ghostsquad** [comment] 2015-09-28 16:17
the package.json file shows this using 1.8, but somehow I doubt this. Math exponent syntax was added in 1.7 `3 ** 2` yet, when I run that in MochaTest, I get a parse error.

```
Running "mochaTest:unit" (mochaTest) task
>> Mocha exploded!
>> Error: In C:\dev\twobit\test\unit\foo.coffee, Parse error on line 6: Unexpected 'MATH'
```

yet running just `mocha` from the commandline gives me the correct value.

**Comment by pghalliday** [comment] 2015-09-29 09:36
`grunt-mocha-test` should have no impact on this. The development dependency is just for test purposes to check the integration of compilers. The version of coffeescript that you use will depend on what you install (the way npm works you will not have installed any of the listed dev dependencies when you installed `grunt-mocha-test`). If you post your project I may have time to take a quick look and figure out what the problem is with your configuration.

**Comment by ghostsquad** [comment] 2015-09-29 17:22
here is the last commit I was using with Grunt. 
https://github.com/ghostsquad/twobit/commit/411c89db5273917c23dce71f68d1bde474998a55

here's what I tested

| Command     | Result | Notes                                         |
|-------------|--------|-----------------------------------------------|
| mocha       | OK     |                                               |
| grunt build | OK     | the resulting javascript in /js looks correct |
| grunt test  | ERROR  |                                               |

consequently, moving over to Gulp has worked flawlessly.

**Comment by pghalliday** [comment] 2015-09-30 07:01
All I can think of is that you didn't specify the require option to use coffee script so it bombed out due to not being valid JS. Anyway good luck with gulp. I've been there too, but these days I mostly just use npm scripts and command line tools

**Comment by ghostsquad** [comment] 2015-09-30 15:08
That's not this issue because all I need to do for mochaTest to work is remove the line that looks like `3 ** 2`. :(

**Comment by pghalliday** [comment] 2015-10-19 09:17
Well, as I mentioned before the version of coffeescript you use doesn't come from `grunt-mocha-test` so I can't see how that's the issue. In the interest of house keeping and given that you have `gulp` working fine. I'm going to close this issue. Thanks for reporting it anyway and I'll keep my eyes open for anything similar

**Closed by pghalliday** 2015-10-19 09:17 UTC
